// @generated by protobuf-ts 2.8.0 with parameter output_javascript
// @generated from protobuf file "hehe.proto" (package "hehepb", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { asd } from "./test";
/**
 * @generated from protobuf message hehepb.mine
 */
export interface mine {
    /**
     * @generated from protobuf field: string detail = 1;
     */
    detail: string;
    /**
     * @generated from protobuf oneof: details
     */
    details: {
        oneofKind: "asd";
        /**
         * @generated from protobuf field: testpb.asd asd = 2;
         */
        asd: asd;
    } | {
        oneofKind: undefined;
    };
}
declare class mine$Type extends MessageType<mine> {
    constructor();
    create(value?: PartialMessage<mine>): mine;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: mine): mine;
    internalBinaryWrite(message: mine, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message hehepb.mine
 */
export declare const mine: mine$Type;
export {};
