// @generated by protobuf-ts 2.8.0 with parameter output_javascript
// @generated from protobuf file "test.proto" (package "testpb", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message testpb.asd
 */
export interface asd {
    /**
     * @generated from protobuf field: string test_string = 1;
     */
    testString: string;
    /**
     * @generated from protobuf field: int32 test_int = 2;
     */
    testInt: number;
    /**
     * @generated from protobuf field: bool test_bool = 3;
     */
    testBool: boolean;
}
declare class asd$Type extends MessageType<asd> {
    constructor();
    create(value?: PartialMessage<asd>): asd;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: asd): asd;
    internalBinaryWrite(message: asd, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message testpb.asd
 */
export declare const asd: asd$Type;
export {};
